{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import langgraph\n",
    "import pathway as pw\n",
    "from dotenv import load_dotenv"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "AIzaSyCreM1_CI9SzRwJYWYmnd4is36H_8w__mo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "This is not the real Pathway package.\n",
      "Visit https://pathway.com/developers/ to get Pathway.\n",
      "Already tried that? Visit https://pathway.com/troubleshooting/ to get help.\n",
      "Note: your platform is Windows-10-10.0.22631-SP0, your Python is CPython 3.10.16.\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "module 'pathway' has no attribute 'io'\nThis is not the real Pathway package.\nVisit https://pathway.com/developers/ to get Pathway.\nAlready tried that? Visit https://pathway.com/troubleshooting/ to get help.\nNote: your platform is Windows-10-10.0.22631-SP0, your Python is CPython 3.10.16.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[5], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m table \u001b[38;5;241m=\u001b[39m \u001b[43mpw\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mio\u001b[49m\u001b[38;5;241m.\u001b[39mgdrive\u001b[38;5;241m.\u001b[39mread(\n\u001b[0;32m      2\u001b[0m     object_id\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m1Z8z4craj36ighb8hzUzeM76OOgpUdsKr\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m      3\u001b[0m     service_user_credentials_file\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcredentials.json\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m      4\u001b[0m )\n\u001b[0;32m      6\u001b[0m pw\u001b[38;5;241m.\u001b[39mrun()\n",
      "File \u001b[1;32mc:\\a\\envs\\env2\\lib\\site-packages\\pathway\\__init__.py:61\u001b[0m, in \u001b[0;36m__getattr__\u001b[1;34m(name)\u001b[0m\n\u001b[0;32m     59\u001b[0m _warn(warning)\n\u001b[0;32m     60\u001b[0m error \u001b[38;5;241m=\u001b[39m error \u001b[38;5;241m+\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m+\u001b[39m warning\n\u001b[1;32m---> 61\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mAttributeError\u001b[39;00m(error)\n",
      "\u001b[1;31mAttributeError\u001b[0m: module 'pathway' has no attribute 'io'\nThis is not the real Pathway package.\nVisit https://pathway.com/developers/ to get Pathway.\nAlready tried that? Visit https://pathway.com/troubleshooting/ to get help.\nNote: your platform is Windows-10-10.0.22631-SP0, your Python is CPython 3.10.16."
     ]
    }
   ],
   "source": [
    "table = pw.io.gdrive.read(\n",
    "    object_id=\"1Z8z4craj36ighb8hzUzeM76OOgpUdsKr\",\n",
    "    service_user_credentials_file=\"credentials.json\"\n",
    ")\n",
    "\n",
    "pw.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "This is not the real Pathway package.\n",
      "Visit https://pathway.com/developers/ to get Pathway.\n",
      "Already tried that? Visit https://pathway.com/troubleshooting/ to get help.\n",
      "Note: your platform is Windows-10-10.0.22631-SP0, your Python is CPython 3.10.16.\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "module 'pathway' has no attribute '__version__'\nThis is not the real Pathway package.\nVisit https://pathway.com/developers/ to get Pathway.\nAlready tried that? Visit https://pathway.com/troubleshooting/ to get help.\nNote: your platform is Windows-10-10.0.22631-SP0, your Python is CPython 3.10.16.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[7], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[43mpw\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m__version__\u001b[49m\n",
      "File \u001b[1;32mc:\\a\\envs\\env2\\lib\\site-packages\\pathway\\__init__.py:61\u001b[0m, in \u001b[0;36m__getattr__\u001b[1;34m(name)\u001b[0m\n\u001b[0;32m     59\u001b[0m _warn(warning)\n\u001b[0;32m     60\u001b[0m error \u001b[38;5;241m=\u001b[39m error \u001b[38;5;241m+\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m+\u001b[39m warning\n\u001b[1;32m---> 61\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mAttributeError\u001b[39;00m(error)\n",
      "\u001b[1;31mAttributeError\u001b[0m: module 'pathway' has no attribute '__version__'\nThis is not the real Pathway package.\nVisit https://pathway.com/developers/ to get Pathway.\nAlready tried that? Visit https://pathway.com/troubleshooting/ to get help.\nNote: your platform is Windows-10-10.0.22631-SP0, your Python is CPython 3.10.16."
     ]
    }
   ],
   "source": [
    "pw.__version__\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "env2",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
